name: Build
on:
  push:

jobs:
  binary:
    name: Build binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - name: Install dependencies
        run: go get -v ./...
      - name: Build
        run: cd cmd/shanghai && CGO_ENABLED=0 go build -o ../../shanghai
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: binary
          path: shanghai
  completions:
    name: Generate completions
    runs-on: ubuntu-latest
    needs: binary
    strategy:
      matrix:
        shell: [bash, zsh, fish, powershell]
    steps:
      - uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: binary
      - name: Change permissions
        run: chmod +x shanghai
      - name: Generate completions
        run: ./shanghai completion ${{ matrix.shell }} > ./${{ matrix.shell }}_completion
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.shell }}-completions
          path: ./${{ matrix.shell }}_completion
